### ISSUE TITLE
Upgrade to Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by RoLYroLLs** [loekd/ServiceFabric.ServiceBus#13]
Hello,

I've found my way to this great project many times and I'm ready to start using it by downloading the nugget `ServiceFabric.ServiceBus.Services`. My only problem is my current WorkerRole (which I'm upgrading to `Stateless Service` in `Service Fabric`) uses the updated `Microsoft.Azure.ServiceBus` instead of `Microsoft.ServiceBus`.

Do you have any plans to upgrade any of these to the newest `Microsoft.Azure.ServiceBus` or making a separate `ServiceFabric.ServiceBus.Services` to be used with `Service Fabric`?

**Comment by loekd** [comment]
Thanks for the kind words.
We can start implementing this for sure.
What kind of functionality do you require? Queues or Topics? Do you use sessions?

**Comment by loekd** [comment]
Have a look at the start implementation [here](https://github.com/loekd/ServiceFabric.ServiceBus/tree/NetstandardPackage/ServiceFabric.ServiceBus.Services.Netstd) and feel free to contribute.

**Comment by RoLYroLLs** [comment]
@loekd wow! thanks for the fast response to this.

I'm very new to `Service Bus`. I only got interested in it through the series of articles (https://jonhilton.net/2016/02/01/how-not-to-send-emails-from-your-web-site-part-1/) I read about 4 weeks ago.

I'm currently only interested in Topics and Subscriptions. As for Sessions, I don't know if I should be using them. I don't totally know their pros/cons.

My first Service Bus project basically consists of writing a process that records all emails sent by our website to our db. A Message will be sent to our Topic with the row identifier that was just added. A Stateless Service will receive those Messages, retrieve the email contents from the db and send out the emails.

**Comment by loekd** [comment]
@RoLYroLLs  can you give this **preview** version a go and please provide feedback here?
It works slightly different than the full-Fx version due to differences between the 2 SB SDK's. But by using the old demo code you shouldn't have much trouble getting it to run.

https://www.nuget.org/packages/ServiceFabric.ServiceBus.Services.Netstd/6.0.0-preview

**Comment by RoLYroLLs** [comment]
@loekd thanks! I won't be able to try it until Monday. I'll be sure to report my findings.

**Comment by RoLYroLLs** [comment]
@loekd I'm finally starting to try to implement this, but I'm having trouble understanding how to with my limited knowledge.

Specifically, taking from the sample [here](https://github.com/loekd/ServiceFabric.ServiceBus/blob/d958651f47838271c765c9fe818bd8d2088e6aee/ServiceFabric.ServiceBus.Demo/SampleSubscriptionListeningStatelessService/SampleSubscriptionListeningStatelessService.cs#L25-L47), I got this far with errors which I'm trying to figure out.

		protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners() {
			var serviceBusTopicName = TopicNameMessageReceiver;
			var serviceBusSubscriptionName = SubscriptionNameMessageReceiver;
			Action<string> logAction = log => ServiceEventSource.Current.ServiceMessage(this.Context, log);

			yield return new ServiceInstanceListener(context => new
				ServiceBusSubscriptionCommunicationListener(
					new Handler() // TODO: figure out how to implement this
					, context
					, serviceBusTopicName
					, serviceBusSubscriptionName) {
						LogAction = logAction,
					}, "StatelessService-ServiceBusSubscriptionListener");
		}
	}

	internal sealed class Handler : DefaultServiceBusMessageReceiver {
		public Handler(IServiceBusCommunicationListener receiver, Action<string> logAction = null) : base(receiver, logAction) { }

		protected override Task ReceiveMessageImplAsync(ServiceBusMessage message, CancellationToken cancellationToken) {
			
		}
	}

**Comment by RoLYroLLs** [comment]
@loekd this is probably off topic but I'll ask anyways and you can direct me to ask separately or keep it:

The service I'm trying to build is going to process messages and once it does, it needs to send a message to another topic (call it "Topic2"). Does the architecture of this library support that? Look at the current version 5.x.x it feels as if I would have to created a connection to Topic2 every time i process of message, which i prefer not to do, or keep a variable handy outside of the listener.

Am I not understanding good/proper way of writing this?

**Comment by loekd** [comment]
1. Once you have received a Service Bus message, it is passed to your handler. The handler needs to process the message, so it can be removed / remove it from the queue. Read this about [payload](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messages-payloads) handling.

2. The client library is not converted yet. But it's quite simple to send messages. You'd create a [TopicClient](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions) inside your service to send messages. The client can live as long as the service itself, so open it when the service starts up.

**Comment by RoLYroLLs** [comment]
@loekd Thank you. I can send and receive messages so far. I guess what I'm trying to say is, in the handler, is where I create the `TopicClient`? Or do I have to create it before calling the handler?

**Comment by loekd** [comment]
If you need to either complete or abort the incoming message, based on the result of sending the new message, I'd create the client inside the handler.

**Comment by RoLYroLLs** [comment]
@loekd thank you. =)

**Comment by loekd** [comment]
Your're welcome!
I think it's ok to close this issue now. Please reopen if needed.
