### ISSUE TITLE
DefaultServiceBusMessageReceiver protected IServiceBusCommunicationListener 

### ISSUE THREAD

**Issue by mack0196** [loekd/ServiceFabric.ServiceBus#14]
Change the accessibility of DefaultServiceBusMessageReceiver private readonly IServiceBusCommunicationListener _receiver to protected.

Overriding the virtual HandleReceiveMessageError to add failure properties requires access to the IServiceBusCommunicatorionListener _reciever.

**Comment by loekd** [comment]
Could please you post some code or make a PR to indicate your requirements?

**Comment by loekd** [comment]
Added to v6.0.3
