### ISSUE TITLE
Create ServiceFabric App Topic Listener , throws Exception When Deployed to Local Cluster

### ISSUE THREAD

**Issue by chriswhinds** [loekd/ServiceFabric.ServiceBus#19]

**Comment by chriswhinds** [comment]
Im developing a Service Fabric ServiceBus Topic Listener during a deploy/debug it throws an exception  
"Exception thrown: 'System.DllNotFoundException' in Microsoft.WindowsAzure.Configuration.dll
An exception of type 'System.DllNotFoundException' occurred in Microsoft.WindowsAzure.Configuration.dll but was not handled in user code

Package dependencies:
ServiceFabric.ServiceBus.Service 6.0.2
Microsoft.WindowsAzure.ConfigurationManager 3.2.3
Microsoft.ServiceFabric 6.4.624

Any Ideas on how to fix this?

![servicefabricservicebusexception](https://user-images.githubusercontent.com/20133633/51264099-a881cd80-1983-11e9-968e-3d242eb548cf.PNG)

 Fabric App Dependencies 
![ftsauditdeps](https://user-images.githubusercontent.com/20133633/51264313-38277c00-1984-11e9-97da-8ba9d3aed56a.PNG)

**Comment by loekd** [comment]
This issue seems related: https://github.com/Azure/azure-storage-net/issues/596 
Does that help?

**Comment by loekd** [comment]
Closed due to inactivity

**Comment by chriswhinds** [comment]
Thanks the solution to this problem was to use the correct versions Dependent libraries.
All Good now. 
Regards
