### ISSUE TITLE
The QueueClient is not closed gracefully when MaxConcurrentCalls is greater than 1

### ISSUE THREAD

**Issue by Tankatronic** [loekd/ServiceFabric.ServiceBus#20]
**Problem**
Currently, a graceful shutdown of the `QueueClient` is handled with a `ManualResetEvent`. When `CloseAsync` is called, it will wait until the `ManualResetEvent` is Set, and then close the Queue. However this logic quickly breaks down in scenarios where `MaxConcurrentCalls` is greater than 1, as multiple threads will `Set` and `Reset` and the state of the semaphore is no longer representative of what is being processed.

**Recommended Solution**
A `ConcurrentDictionary` can be used to keep track of messages that are currently being processed. Instead of waiting for the `ManualResetEvent` to Reset, it can wait for the `ConcurrentDictionary` to be empty. The message handler will also need to be updated, so that if `CloseAsync` has been called, a flag can be set that will prevent new messages from being processed. this would have to be done with a `Task.Delay` or similar call, as returning immediately from the message handler will just result in the message potentially being picked up again and possibly dead lettered if it is picked up too many times.

**Comment by loekd** [comment]
You're correct, this is a bug. Can you do a PR and contribute to this package?

**Comment by Tankatronic** [comment]
Sure thing. Hopefully by next week!

**Comment by Tankatronic** [comment]
@loekd Would you like the new logic for waiting for processing messages to finish to wait indefinitely, or have a configurable timeout with a default value? 

I am concerned about a potential deadlock, if the thread running `ServiceBusQueueCommunicationListener.ReceiveMessageAsync` were to terminate for some reason and the logic in the `finally` block would not execute and never remove the processing message. The current implementation does not have a timeout and will wait indefinitely.

**Comment by loekd** [comment]
Makes sense. I think a safe timeout would be just over 1 minute, which is the default SB message lock duration. Indeed, no need to wait indefinitely.

And maybe you could use a semaphore instead, start at `MaxConcurrentCalls`, enter inside the `ReceiveMessageAsync` while processing a message. Enter it `MaxConcurrentCalls` times in `CloseAsync`? Might be easier than doing your own housekeeping inside a dictionary.

**Comment by loekd** [comment]
The new version is available on Nuget now. Sorry for the delay, I hadn't noticed the build failure.
