### ISSUE TITLE
Potential issue with async handling

### ISSUE THREAD

**Issue by softeering** [loekd/ServiceFabric.ServiceBus#3]
Hi,

Thanks for this interesting repo.
I had a look at the code and it seems there is an issue with the ASYNC pattern usage.

Let's take the AutoCompleteServiceBusMessageReceiver as an example.
In the method called ReceiveMessageAsync, you're returning the task without waiting for its completion and at the same time, you Complete / Abandon the message (Actually, the CATCH block will never be hit)

```
public Task ReceiveMessageAsync(BrokeredMessage message, CancellationToken cancellationToken)
{
    Task result = null;
    try
    {
        result = ReceiveMessageImplAsync(message, cancellationToken);
        message.Complete();
    }
    catch
    {
        message.Abandon();
        //catch all to avoid process crash.
        //assuming implementing code handles exceptions.
    }
    return result;
}
```

Isn't this wrong?
Shouldn't it be?

```
public async Task ReceiveMessageAsync(BrokeredMessage message, CancellationToken cancellationToken)
{
    try
    {
        // need to await here before calling Complete()
        await ReceiveMessageImplAsync(message, cancellationToken).ConfigureAwait(false);
        message.Complete();
    }
    catch
    {
        // automatically abandon on error - the lock is released on the queued message
        message.Abandon();
    }
}
```

-David

**Comment by softeering** [comment]
Oh and, another way of doing it would be:

```
public Task ReceiveMessageAsync(BrokeredMessage message, CancellationToken cancellationToken)
{
    return ReceiveMessageImplAsync(message, cancellationToken).ContinueWith(t =>
    {
        if (t.IsFaulted)
            message.Abandon();
        else
            message.Complete();
    });
}
```

-David

**Comment by loekd** [comment]
Thanks for taking the time to look at the code. I've posted a new version (3.1.0) that should resolve the issue. More or less what you suggested in the first comment.

**Comment by softeering** [comment]
Thanks for the update. 
Your repo helped me understanding how to implement a custom listener... really appreciated

-David
