### ISSUE TITLE
Why ReceiveBatch(..) instead of OnMessageAsync(..)

### ISSUE THREAD

**Issue by adminnz** [loekd/ServiceFabric.ServiceBus#6]
Could you explain what your reasoning is behind using _serviceBusClient.ReceiveBatch(..) rather than _serviceBusClient.OnMessageAsync(..) ?

Wouldn't it be better to leave the message fetching up to the QueueClient/SubscriptionClient ?

**Comment by loekd** [comment]
It would save some code indeed. But according to the docs, OnMessage does a Receive call under the hood. I think that means that every message is retrieved separately, which results in higher overhead. I'll do some digging in the sources.

**Comment by adminnz** [comment]
Also have you looked at using Azure WebJobs and using the [ServiceBusTrigger] attribute?
[Web Jobs Service Bus Sample](https://github.com/Azure/azure-webjobs-sdk-samples/tree/master/BasicSamples/ServiceBus)

**Comment by loekd** [comment]
Defining `PrefetchCount`seems to be sufficient to prevent high overhead. 

I'm now thinking of changing the default into `OnMessageAsync`and adding a new communication listener that handles batches. Any thoughts?

**Comment by adminnz** [comment]
That would seam a good idea. It would be nice if Azure Service Bus had a push based queue & topic client (like nearly every other message queue system out there).

**Comment by gmfx** [comment]
Without digging into the specifics and from an API consumer perspective I believe this sounds like a great idea : "changing the default into OnMessageAsyncand adding a new communication listener that handles batches. "

**Comment by loekd** [comment]
the new version (4.0.0) is live, have a look! Let me know what you think.
