### ISSUE TITLE
Purpose of ServiceFabric.ServiceBus.Clients

### ISSUE THREAD

**Issue by promontis** [loekd/ServiceFabric.ServiceBus#8]
I was wondering what the purpose is of the ServiceFabric.ServiceBus.Clients library.

Shouldn't we be able to just use the native service bus client to sent messages? What are the pros for using the ServiceFabric.ServiceBus.Clients library, when comparing it to the native service bus client?

**Comment by loekd** [comment]
Feel free to use any way you see fit to send messages. 

The client library adds abstraction, so you don't need to know the service bus location & credentials. You only provide the name of the stateless service you want to talk to. (It doesn't support partitioning.)

Thanks for your comment!
